sudo: required

services:
  - docker


before_install:
  - docker build -t sajwanmanoj/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true sajwanmanoj/docker-react npm run test 


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-979155780936"
  bucket_path: "docker-react"
  on:
    branch: master 
